// <auto-generated />
namespace BlackList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Login_To_Website : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Login_To_Website));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301403224_Login_To_Website"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
