// <auto-generated />
namespace BlackList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class null_previousmessageid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(null_previousmessageid));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141419323_null_previousmessageid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
